title   NyxOS — Persistent (x86_64)
linux   /arch/boot/x86_64/vmlinuz-linux
initrd  /arch/boot/intel-ucode.img
initrd  /arch/boot/amd-ucode.img
initrd  /arch/boot/x86_64/initramfs-linux.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ARCHISO_LABEL% lsm=landlock,lockdown,yama,integrity,apparmor,bpf cow_label=NYXOS_PERSIST quiet
