#
# NyxOS installed-system pacman.conf (mirrors the profile's build-time one).
#
[options]
Architecture = auto
Color
ParallelDownloads = 5
CheckSpace
SigLevel    = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[blackarch]
SigLevel = Required DatabaseOptional
Server = https://blackarch.org/blackarch/$repo/os/$arch
